from __future__ import annotations

from pathlib import Path
from typing import Any


def generate_deploy_config(
    task_dir: str | Path,
    class_names: list[str],
    config: dict[str, Any],
    bin_path: str | Path | None = None,
    onnx_check: dict[str, Any] | None = None,
) -> dict[str, Any]:
    task = Path(task_dir)
    target = task / "configs" / "deploy_config.py"
    target.parent.mkdir(parents=True, exist_ok=True)
    classes_repr = "[" + ", ".join(repr(name) for name in class_names) + "]"
    content = f'''# Auto-generated by RDK ModelPilot.

MODEL_PATH = "/userdata/model.bin"
INPUT_SIZE = ({int(config.get("default_imgsz", 640))}, {int(config.get("default_imgsz", 640))})
INPUT_FORMAT = "{config.get("runtime_input", "NV12")}"
CLASSES_NUM = {len(class_names)}
CLASS_NAMES = {classes_repr}
STRIDES = [8, 16, 32]
REG = 16
CLS_OUTPUTS = [0, 2, 4]
BOX_OUTPUTS = [1, 3, 5]
POSTPROCESS_TYPE = "YOLO_DFL_6_OUTPUT"
RUNTIME = "hobot_dnn / pyeasy_dnn"
TARGET = "{config.get("target", "RDK X5 bayes-e")}"

# Local build artifacts, useful during deployment packaging.
LOCAL_BIN_PATH = {repr(str(bin_path) if bin_path else "")}
ONNX_STRUCTURE_OK = {bool(onnx_check.get("ok")) if onnx_check else False}
'''
    target.write_text(content, encoding="utf-8")
    return {"ok": True, "deploy_config_path": str(target), "content": content}
